name: Test Github Action
on:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Github Action
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./
        with:
          paths: ${{ github.workspace }}/sample-content